USE LearnWords;
INSERT INTO words (foreignWord, native, audioFile, levelID) VALUES
("close","becsuk","https://www.angolszokincs.com/st/snw/close_verb.mp3",1),
("colour","színez, kiszínez","https://www.angolszokincs.com/st/snw/colour.mp3",1),
("open","kinyit","https://www.angolszokincs.com/st/snw/open.mp3",1),
("colour","szín","https://www.angolszokincs.com/st/snw/colour.mp3",1),
("glass","üveg","https://www.angolszokincs.com/st/snw/glass.mp3",1),
("noise","zaj, lárma","https://www.angolszokincs.com/st/snw/noise.mp3",1),
("paper","papír","https://www.angolszokincs.com/st/snw/paper.mp3",1),
("water","víz","https://www.angolszokincs.com/st/snw/water.mp3",1),
("big","nagy","https://www.angolszokincs.com/st/snw/big.mp3",1),
("black","fekete","https://www.angolszokincs.com/st/snw/black.mp3",1),
("blue","kék","https://www.angolszokincs.com/st/snw/blue.mp3",1),
("brown","barna","https://www.angolszokincs.com/st/snw/brown.mp3",1),
("closed","zárt, bezárt","https://www.angolszokincs.com/st/snw/closed.mp3",1),
("dark","sötét","https://www.angolszokincs.com/st/snw/dark.mp3",1),
("green","zöld","https://www.angolszokincs.com/st/snw/green.mp3",1),
("grey","szürke","https://www.angolszokincs.com/st/snw/grey.mp3",1),
("light","halvány, világos","https://www.angolszokincs.com/st/snw/light.mp3",1),
("long","hosszú","https://www.angolszokincs.com/st/snw/long.mp3",1),
("new","új, újszerű","https://www.angolszokincs.com/st/snw/new.mp3",1),
("orange","narancssárga","https://www.angolszokincs.com/st/snw/orange.mp3",1),
("red","piros/vörös","https://www.angolszokincs.com/st/snw/red.mp3",1),
("short","rövid","https://www.angolszokincs.com/st/snw/short.mp3",1),
("small","kis, kicsi","https://www.angolszokincs.com/st/snw/small.mp3",1),
("white","fehér","https://www.angolszokincs.com/st/snw/white.mp3",1),
("yellow","sárga","https://www.angolszokincs.com/st/snw/yellow.mp3",1),
("die","meghal; kihal, megszűnik","https://www.angolszokincs.com/st/snw/die.mp3",1),
("feel","érzi magát vhogy","https://www.angolszokincs.com/st/snw/feel.mp3",1),
("have","vmilyen baja/betegsége van","https://www.angolszokincs.com/st/snw/have.mp3",1),
("doctor","orvos","https://www.angolszokincs.com/st/snw/doctor.mp3",1),
("hospital","kórház","https://www.angolszokincs.com/st/snw/hospital.mp3",1),
("better","jobban van","https://www.angolszokincs.com/st/snw/better.mp3",1),
("safe","biztonságban levő","https://www.angolszokincs.com/st/snw/safe.mp3",1),
("buy","vesz, vásárol","https://www.angolszokincs.com/st/snw/buy.mp3",1),
("get","beszerez","https://www.angolszokincs.com/st/snw/get.mp3",1),
("pay","fizet vmiért, kifizet vmit","https://www.angolszokincs.com/st/snw/pay.mp3",1),
("bank","bank","https://www.angolszokincs.com/st/snw/bank.mp3",1),
("credit card","hitelkártya","https://www.angolszokincs.com/st/snw/credit_card.mp3",1),
("dollar","dollár","https://www.angolszokincs.com/st/snw/dollar.mp3",1),
("hotel","hotel, szálloda","https://www.angolszokincs.com/st/snw/hotel.mp3",1),
("money","pénz","https://www.angolszokincs.com/st/snw/money.mp3",1),
("restaurant","vendéglő, étterem","https://www.angolszokincs.com/st/snw/restaurant.mp3",1),
("shop","üzlet, bolt","https://www.angolszokincs.com/st/snw/shop.mp3",1),
("shopping","vásárlás, bevásárlás","https://www.angolszokincs.com/st/snw/shopping.mp3",1),
("supermarket","élelmiszer-áruház, ABC-áruház","https://www.angolszokincs.com/st/snw/supermarket.mp3",1),
("cheap","olcsó, nem drága","https://www.angolszokincs.com/st/snw/cheap.mp3",1),
("closed","bezárt, becsukott","https://www.angolszokincs.com/st/snw/closed.mp3",1),
("expensive","drága, költséges","https://www.angolszokincs.com/st/snw/expensive.mp3",1),
("open","nyitva van","https://www.angolszokincs.com/st/snw/open.mp3",1),
("go shopping","bevásárolni megy","https://www.angolszokincs.com/st/snk/r1370.mp3",1),
("invite","meghív vkit vhova","https://www.angolszokincs.com/st/snw/invite.mp3",1),
("love","szerelmes vkibe, szeret vkit","https://www.angolszokincs.com/st/snw/love.mp3",1),
("meet","megismerkedik vkivel","https://www.angolszokincs.com/st/snw/meet.mp3",1),
("meet","találkozik vkivel","https://www.angolszokincs.com/st/snw/meet.mp3",1),
("see","összejön/találkozik vkivel","https://www.angolszokincs.com/st/snw/see.mp3",1),
("visit","látogat, meglátogat vkit","https://www.angolszokincs.com/st/snw/visit.mp3",1),
("brother","fivér, fiútestvér","https://www.angolszokincs.com/st/snw/brother.mp3",1),
("dad","apu","https://www.angolszokincs.com/st/snw/dad.mp3",1),
("daughter","lánygyermek, lány, lánya","https://www.angolszokincs.com/st/snw/daughter.mp3",1),
("family","család","https://www.angolszokincs.com/st/snw/family.mp3",1),
("father","apa","https://www.angolszokincs.com/st/snw/father.mp3",1),
("friend","barát","https://www.angolszokincs.com/st/snw/friend.mp3",1),
("husband","férj","https://www.angolszokincs.com/st/snw/husband.mp3",1),
("mother","édesanya","https://www.angolszokincs.com/st/snw/mother.mp3",1),
("mum","anyuka","https://www.angolszokincs.com/st/snw/mum.mp3",1),
("parent","szülő","https://www.angolszokincs.com/st/snw/parent.mp3",1),
("party","vendégség, buli, parti","https://www.angolszokincs.com/st/snw/party.mp3",1),
("sister","leánytestvér; húg; nővér","https://www.angolszokincs.com/st/snw/sister.mp3",1),
("son","fia vkinek","https://www.angolszokincs.com/st/snw/son.mp3",1),
("wife","feleség","https://www.angolszokincs.com/st/snw/wife.mp3",1),
("carry","visz, cipel, hord","https://www.angolszokincs.com/st/snw/carry.mp3",1),
("catch","elkap, megfog, megragad","https://www.angolszokincs.com/st/snw/catch.mp3",1),
("come","jön","https://www.angolszokincs.com/st/snw/come.mp3",1),
("come","jön, eljön vkivel","https://www.angolszokincs.com/st/snw/come.mp3",1),
("come","megérkezik vhová, ér vhová","https://www.angolszokincs.com/st/snw/come.mp3",1),
("do","csinál, tesz, megtesz, elvégez","https://www.angolszokincs.com/st/snw/do.mp3",1),
("go","megy","https://www.angolszokincs.com/st/snw/go.mp3",1),
("go","megy vhova","https://www.angolszokincs.com/st/snw/go.mp3",1),
("kick","rúg, megrúg, rugdos, rugdal","https://www.angolszokincs.com/st/snw/kick.mp3",1),
("leave","elmegy, elindul, elhagy","https://www.angolszokincs.com/st/snw/leave.mp3",1),
("make","készít, csinál","https://www.angolszokincs.com/st/snw/make.mp3",1),
("put","tesz, letesz, odatesz; rak, odarak; helyez, elhelyez","https://www.angolszokincs.com/st/snw/put.mp3",1),
("run","fut, szalad","https://www.angolszokincs.com/st/snw/run.mp3",1),
("sit","ül","https://www.angolszokincs.com/st/snw/sit.mp3",1),
("take","visz, elvisz, magával visz vmit","https://www.angolszokincs.com/st/snw/take.mp3",1),
("walk","megy, gyalogol; sétál","https://www.angolszokincs.com/st/snw/walk.mp3",1),
("do","segédige kérdésekben/tagadásnál egy másik igével együtt használva","https://www.angolszokincs.com/st/snw/do.mp3",1),
("to","-ni","https://www.angolszokincs.com/st/snw/to.mp3",1),
("get here/there/home/to work, etc.","ide-/oda-/haza-/munkába/stb. ér   vmit","https://www.angolszokincs.com/st/snk/r1265.mp3",1),
("put sth down/in/on, etc.","le/be/rá/stb. tesz/rak/helyez   vmit","https://www.angolszokincs.com/st/snk/r2240.mp3",1),
("help","segít vkinek vmiben","https://www.angolszokincs.com/st/snw/help.mp3",1),
("can","-hat, -het","https://www.angolszokincs.com/st/snw/can_2.mp3",1),
("can","-hat, -het","https://www.angolszokincs.com/st/snw/can_2.mp3",1),
("pair","pár","https://www.angolszokincs.com/st/snw/pair.mp3",1),
("please","legyen szíves, kérem","https://www.angolszokincs.com/st/snw/please.mp3",1),
("thank you","köszönöm","https://www.angolszokincs.com/st/snw/thank_you.mp3",1),
("thanks","köszönöm","https://www.angolszokincs.com/st/snw/thanks.mp3",1),
("would like sth/to do sth","szeretne  vmit","https://www.angolszokincs.com/st/snk/r3048.mp3",1),
("Yes, please","köszönöm, igen/kérek  vmit","https://www.angolszokincs.com/st/snk/r118.mp3",1),
("group","csoport","https://www.angolszokincs.com/st/snw/group.mp3",1),
("part","rész, része vminek","https://www.angolszokincs.com/st/snw/part.mp3",1),
("different","különböző, más","https://www.angolszokincs.com/st/snw/different.mp3",1),
("new","új, másik","https://www.angolszokincs.com/st/snw/new.mp3",1),
("same","ugyanaz","https://www.angolszokincs.com/st/snw/same.mp3",1),
("also","is","https://www.angolszokincs.com/st/snw/also.mp3",1),
("together","együtt; össze-","https://www.angolszokincs.com/st/snw/together.mp3",1),
("too","is, szintén","https://www.angolszokincs.com/st/snw/too.mp3",1),
("why","miért?","https://www.angolszokincs.com/st/snw/why.mp3",1),
("about","-ról, -ről, kapcsolatban vkivel/vmivel","https://www.angolszokincs.com/st/snw/about.mp3",1),
("for","számára, részére, -nak, -nek","https://www.angolszokincs.com/st/snw/for.mp3",1),
("with","-val, -vel","https://www.angolszokincs.com/st/snw/with.mp3",1),
("with","-val, -vel","https://www.angolszokincs.com/st/snw/with.mp3",1),
("and","és","https://www.angolszokincs.com/st/snw/and.mp3",1),
("because","mert","https://www.angolszokincs.com/st/snw/because.mp3",1),
("but","de, hanem, azonban","https://www.angolszokincs.com/st/snw/but.mp3",1),
("or","vagy","https://www.angolszokincs.com/st/snw/or.mp3",1),
("as well","még ... is, valamint","https://www.angolszokincs.com/st/snk/r354.mp3",1),
("the same","ugyanolyan","https://www.angolszokincs.com/st/snk/r2815.mp3",1),
("best","legjobb","https://www.angolszokincs.com/st/snw/best.mp3",1),
("better","jobb","https://www.angolszokincs.com/st/snw/better.mp3",1),
("best","legjobban","https://www.angolszokincs.com/st/snw/best.mp3",1),
("really","nagyon, igazán","https://www.angolszokincs.com/st/snw/really.mp3",1),
("very","nagyon","https://www.angolszokincs.com/st/snw/very.mp3",1),
("than","mint","https://www.angolszokincs.com/st/snw/than.mp3",1),
("a lot","sokkal; nagyon; sokat","https://www.angolszokincs.com/st/snk/r184.mp3",1),
("more beautiful/difficult/easily, etc.","szebb/nehezebb/könnyebben/stb./, -abb, -ebb","https://www.angolszokincs.com/st/snk/r1930.mp3",1),
("not very good/tall/happy, etc.","nem valami jó/magas/boldog/stb.","https://www.angolszokincs.com/st/snk/r2009.mp3",1),
("too small/hard/much, etc.","túl/túlságosan kicsi/kemény/sok/stb.","https://www.angolszokincs.com/st/snk/r2925.mp3",1),
("very much","nagyon; nagyon sok/sokat","https://www.angolszokincs.com/st/snk/r2983.mp3",1),
("business","üzlet, vállalkozás, kereskedelem","https://www.angolszokincs.com/st/snw/business.mp3",1),
("factory","gyár","https://www.angolszokincs.com/st/snw/factory.mp3",1),
("know","tud","https://www.angolszokincs.com/st/snw/know.mp3",1),
("remember","emlékszik","https://www.angolszokincs.com/st/snw/remember.mp3",1),
("think","azt gondolja, azt hiszi","https://www.angolszokincs.com/st/snw/think.mp3",1),
("think","gondol vminek/vmilyennek vkit/vmit","https://www.angolszokincs.com/st/snw/think.mp3",1),
("example","példa vmire","https://www.angolszokincs.com/st/snw/example.mp3",1),
("new","új, ismeretlen","https://www.angolszokincs.com/st/snw/new.mp3",1),
("Don't forget...","nehogy megfeledkezz","https://www.angolszokincs.com/st/snk/r50.mp3",1),
("for example","például","https://www.angolszokincs.com/st/snk/r1194.mp3",1),
("bye","viszlát! szia! sziasztok!","https://www.angolszokincs.com/st/snw/bye.mp3",1),
("good afternoon","jó napot kívánok!","https://www.angolszokincs.com/st/snw/good_afternoon.mp3",1),
("good evening","jó estét kívánok!","https://www.angolszokincs.com/st/snw/good_evening.mp3",1),
("good morning","jó reggelt kívánok!","https://www.angolszokincs.com/st/snw/good_morning.mp3",1),
("good night","jó éjszakát!","https://www.angolszokincs.com/st/snw/good_night.mp3",1),
("goodbye","viszontlátásra!","https://www.angolszokincs.com/st/snw/goodbye.mp3",1),
("hello","jó napot! szia!","https://www.angolszokincs.com/st/snw/hello.mp3",1),
("hi","helló!","https://www.angolszokincs.com/st/snw/hi.mp3",1),
("Excuse me","bocsánat!, elnézést kérek","https://www.angolszokincs.com/st/snk/r54.mp3",1),
("(Good) morning","jó reggelt kívánok!","https://www.angolszokincs.com/st/snk/r1.mp3",1),
("Happy Birthday/New Year, etc.","boldog születésnapot!/új évet!/stb.","https://www.angolszokincs.com/st/snk/r58.mp3",1),
("see you","viszlát!","https://www.angolszokincs.com/st/snk/r2394.mp3",1),
("see you later","viszlát! később találkozunk!","https://www.angolszokincs.com/st/snk/r2395.mp3",1),
("see you later/soon/tomorrow, etc.","viszlát! később/hamarosan/holnap/stb. találkozunk!","https://www.angolszokincs.com/st/snk/r2396.mp3",1),
("see you soon","viszlát! hamarosan találkozunk!","https://www.angolszokincs.com/st/snk/r2397.mp3",1),
("Well done!","gratulálok!","https://www.angolszokincs.com/st/snk/r108.mp3",1),
("good","jó! jól van!","https://www.angolszokincs.com/st/snw/good.mp3",1),
("oh","ó!","https://www.angolszokincs.com/st/snw/oh.mp3",1),
("oh","ó ...!","https://www.angolszokincs.com/st/snw/oh.mp3",1),
("well","nos, hát","https://www.angolszokincs.com/st/snw/well.mp3",1),
("he","ő","https://www.angolszokincs.com/st/snw/he.mp3",1),
("her","őt; neki, őneki","https://www.angolszokincs.com/st/snw/her.mp3",1),
("him","őt, neki; őneki","https://www.angolszokincs.com/st/snw/him.mp3",1),
("I","én","https://www.angolszokincs.com/st/snw/i.mp3",1),
("it","ő, az; őt, azt; neki, annak","https://www.angolszokincs.com/st/snw/it.mp3",1),
("me","engem; nekem; én","https://www.angolszokincs.com/st/snw/me.mp3",1),
("she","ő","https://www.angolszokincs.com/st/snw/she.mp3",1),
("them","őket, azokat; nekik, azoknak","https://www.angolszokincs.com/st/snw/them.mp3",1),
("they","ők, azok","https://www.angolszokincs.com/st/snw/they.mp3",1),
("us","minket, bennünket; nekünk","https://www.angolszokincs.com/st/snw/us.mp3",1),
("we","mi","https://www.angolszokincs.com/st/snw/we.mp3",1),
("you","ön, maga; te; önt, magát; téged; önök, maguk; ti; önöket, magukat; titeket","https://www.angolszokincs.com/st/snw/you.mp3",1),
("a","egy","https://www.angolszokincs.com/st/snw/a.mp3",1),
("an","egy","https://www.angolszokincs.com/st/snw/an.mp3",1),
("the","a, az","https://www.angolszokincs.com/st/snw/the.mp3",1),
("the","a, az","https://www.angolszokincs.com/st/snw/the.mp3",1),
("the","a, az","https://www.angolszokincs.com/st/snw/the.mp3",1),
("thing","dolog, tárgy","https://www.angolszokincs.com/st/snw/thing.mp3",1),
("anything","valami","https://www.angolszokincs.com/st/snw/anything.mp3",1),
("anything","bármi, akármi","https://www.angolszokincs.com/st/snw/anything.mp3",1),
("each","mindegyik; mindenki, ki-ki","https://www.angolszokincs.com/st/snw/each.mp3",1),
("it","az, azt","https://www.angolszokincs.com/st/snw/it.mp3",1),
("something","valami","https://www.angolszokincs.com/st/snw/something.mp3",1),
("that","az","https://www.angolszokincs.com/st/snw/that.mp3",1),
("that","az","https://www.angolszokincs.com/st/snw/that.mp3",1),
("what","mi? mit?","https://www.angolszokincs.com/st/snw/what.mp3",1),
("who","ki? kik? kit? kiket?","https://www.angolszokincs.com/st/snw/who.mp3",1),
("a","egy","https://www.angolszokincs.com/st/snw/a.mp3",1),
("all","mind, minden, mindannyian","https://www.angolszokincs.com/st/snw/all.mp3",1),
("any","valami, valamelyik","https://www.angolszokincs.com/st/snw/any.mp3",1),
("any","akármelyik, bármelyik","https://www.angolszokincs.com/st/snw/any.mp3",1),
("both","mindkét","https://www.angolszokincs.com/st/snw/both.mp3",1),
("each","mindegyik, minden egyes","https://www.angolszokincs.com/st/snw/each.mp3",1),
("every","mindegyik, minden egyes","https://www.angolszokincs.com/st/snw/every.mp3",1),
("no","semmi; semmilyen","https://www.angolszokincs.com/st/snw/no.mp3",1),
("other","más, másik, egyéb","https://www.angolszokincs.com/st/snw/other.mp3",1),
("that","az","https://www.angolszokincs.com/st/snw/that.mp3",1),
("that","az","https://www.angolszokincs.com/st/snw/that.mp3",1),
("these","ezek","https://www.angolszokincs.com/st/snw/these.mp3",1),
("this","ez","https://www.angolszokincs.com/st/snw/this.mp3",1),
("this","ez a, ez az","https://www.angolszokincs.com/st/snw/this.mp3",1),
("those","azok","https://www.angolszokincs.com/st/snw/those.mp3",1),
("what","milyen? mennyi?","https://www.angolszokincs.com/st/snw/what.mp3",1),
("which","melyik? melyiket?","https://www.angolszokincs.com/st/snw/which.mp3",1),
("things","dolgok, holmi, felszerelés","https://www.angolszokincs.com/st/snk/r2858.mp3",1),
("have","van","https://www.angolszokincs.com/st/snw/have.mp3",1),
("her","az ő -ja, -je, -jai, -jei","https://www.angolszokincs.com/st/snw/her.mp3",1),
("his","az ő -ja, -je, -jai, -jei","https://www.angolszokincs.com/st/snw/his.mp3",1),
("its","","https://www.angolszokincs.com/st/snw/its.mp3",1),
("my","az m","https://www.angolszokincs.com/st/snw/my.mp3",1),
("our","a mi -unk, -ünk, -nk","https://www.angolszokincs.com/st/snw/our.mp3",1),
("their","az ő valamijük/vmijeik","https://www.angolszokincs.com/st/snw/their.mp3",1),
("your","az ön vmije","https://www.angolszokincs.com/st/snw/your.mp3",1),
("of","valakinek/valaminek a valamije/valakije","https://www.angolszokincs.com/st/snw/of.mp3",1),
("bathroom","fürdőszoba","https://www.angolszokincs.com/st/snw/bathroom.mp3",1),
("bedroom","hálószoba","https://www.angolszokincs.com/st/snw/bedroom.mp3",1),
("dining room","ebédlő","https://www.angolszokincs.com/st/snw/dining_room.mp3",1),
("door","ajtó; bejárati ajtó","https://www.angolszokincs.com/st/snw/door.mp3",1),
("flat","lakás","https://www.angolszokincs.com/st/snw/flat.mp3",1),
("floor","padló, padlózat","https://www.angolszokincs.com/st/snw/floor.mp3",1),
("garden","kert","https://www.angolszokincs.com/st/snw/garden.mp3",1),
("home","otthon","https://www.angolszokincs.com/st/snw/home.mp3",1),
("house","családi ház; ház, épület","https://www.angolszokincs.com/st/snw/house_noun.mp3",1),
("kitchen","konyha","https://www.angolszokincs.com/st/snw/kitchen.mp3",1),
("living room","nappali","https://www.angolszokincs.com/st/snw/living_room.mp3",1),
("room","szoba; terem","https://www.angolszokincs.com/st/snw/room.mp3",1),
("swimming pool","uszoda, úszómedence","https://www.angolszokincs.com/st/snw/swimming_pool.mp3",1),
("toilet","vécé, WC","https://www.angolszokincs.com/st/snw/toilet.mp3",1),
("wall","fal","https://www.angolszokincs.com/st/snw/wall.mp3",1),
("window","ablak","https://www.angolszokincs.com/st/snw/window.mp3",1),
("clean","tisztít, kitisztít, megtisztít; takarít, kitakarít","https://www.angolszokincs.com/st/snw/clean.mp3",1),
("wash","mos, megmos","https://www.angolszokincs.com/st/snw/wash.mp3",1),
("bag","zacskó; táska, szatyor","https://www.angolszokincs.com/st/snw/bag.mp3",1),
("bath","fürdőkád","https://www.angolszokincs.com/st/snw/bath.mp3",1),
("bed","ágy","https://www.angolszokincs.com/st/snw/bed.mp3",1),
("box","doboz","https://www.angolszokincs.com/st/snw/box.mp3",1),
("CD","CD","https://www.angolszokincs.com/st/snw/cd.mp3",1),
("CD player","CD lejátszó","https://www.angolszokincs.com/st/snw/cd_player.mp3",1),
("chair","szék","https://www.angolszokincs.com/st/snw/chair.mp3",1),
("clock","óra","https://www.angolszokincs.com/st/snw/clock.mp3",1),
("cup","csésze","https://www.angolszokincs.com/st/snw/cup.mp3",1),
("desk","íróasztal","https://www.angolszokincs.com/st/snw/desk.mp3",1),
("DVD","DVD","https://www.angolszokincs.com/st/snw/dvd.mp3",1),
("glass","pohár","https://www.angolszokincs.com/st/snw/glass.mp3",1),
("key","kulcs","https://www.angolszokincs.com/st/snw/key.mp3",1),
("knife","kés","https://www.angolszokincs.com/st/snw/knife.mp3",1),
("paint","festék","https://www.angolszokincs.com/st/snw/paint.mp3",1),
("plate","tányér","https://www.angolszokincs.com/st/snw/plate.mp3",1),
("radio","rádió, rádiókészülék","https://www.angolszokincs.com/st/snw/radio.mp3",1),
("shower","zuhany, zuhanyozó","https://www.angolszokincs.com/st/snw/shower.mp3",1),
("table","asztal","https://www.angolszokincs.com/st/snw/table.mp3",1),
("television","televízió, televíziókészülék","https://www.angolszokincs.com/st/snw/television.mp3",1),
("TV","TV, televízió","https://www.angolszokincs.com/st/snw/tv.mp3",1),
("clean","tiszta","https://www.angolszokincs.com/st/snw/clean.mp3",1),
("of","valami valamit tartalmaz","https://www.angolszokincs.com/st/snw/of.mp3",1),
("do the cleaning/cooking, etc.","elvégzi/megcsinálja a takarítást/főzést, stb.","https://www.angolszokincs.com/st/snk/r1025.mp3",1),
("afternoon","délután","https://www.angolszokincs.com/st/snw/afternoon.mp3",1),
("day","nap","https://www.angolszokincs.com/st/snw/day.mp3",1),
("evening","este","https://www.angolszokincs.com/st/snw/evening.mp3",1),
("hour","óra","https://www.angolszokincs.com/st/snw/hour.mp3",1),
("minute","perc","https://www.angolszokincs.com/st/snw/minute_noun.mp3",1),
("month","hónap","https://www.angolszokincs.com/st/snw/month.mp3",1),
("month","hónap","https://www.angolszokincs.com/st/snw/month.mp3",1),
("morning","reggel; délelőtt; hajnal","https://www.angolszokincs.com/st/snw/morning.mp3",1),
("night","éjszaka","https://www.angolszokincs.com/st/snw/night.mp3",1),
("night","este","https://www.angolszokincs.com/st/snw/night.mp3",1),
("quarter","negyedóra","https://www.angolszokincs.com/st/snw/quarter.mp3",1),
("summer","nyár","https://www.angolszokincs.com/st/snw/summer.mp3",1),
("week","hét","https://www.angolszokincs.com/st/snw/week.mp3",1),
("week","hétköznapok","https://www.angolszokincs.com/st/snw/week.mp3",1),
("weekend","hétvége","https://www.angolszokincs.com/st/snw/weekend.mp3",1),
("winter","tél","https://www.angolszokincs.com/st/snw/winter.mp3",1),
("year","év","https://www.angolszokincs.com/st/snw/year.mp3",1),
("a.m.","délelőtt","https://www.angolszokincs.com/st/snw/a_m_.mp3",1),
("p.m.","délután/este","https://www.angolszokincs.com/st/snw/p_m_.mp3",1),
("April","április","https://www.angolszokincs.com/st/snw/april.mp3",1),
("August","augusztus","https://www.angolszokincs.com/st/snw/august.mp3",1),
("December","december","https://www.angolszokincs.com/st/snw/december.mp3",1),
("February","február","https://www.angolszokincs.com/st/snw/february.mp3",1),
("January","január","https://www.angolszokincs.com/st/snw/january.mp3",1),
("July","július","https://www.angolszokincs.com/st/snw/july.mp3",1),
("June","június","https://www.angolszokincs.com/st/snw/june.mp3",1),
("March","március","https://www.angolszokincs.com/st/snw/march.mp3",1),
("May","május","https://www.angolszokincs.com/st/snw/may.mp3",1),
("November","november","https://www.angolszokincs.com/st/snw/november.mp3",1),
("October","október","https://www.angolszokincs.com/st/snw/october.mp3",1),
("September","szeptember","https://www.angolszokincs.com/st/snw/september.mp3",1),
("Friday","péntek","https://www.angolszokincs.com/st/snw/friday.mp3",1),
("Monday","hétfő","https://www.angolszokincs.com/st/snw/monday.mp3",1),
("Saturday","szombat","https://www.angolszokincs.com/st/snw/saturday.mp3",1),
("Sunday","vasárnap","https://www.angolszokincs.com/st/snw/sunday.mp3",1),
("Thursday","csütörtök","https://www.angolszokincs.com/st/snw/thursday.mp3",1),
("Tuesday","kedd","https://www.angolszokincs.com/st/snw/tuesday.mp3",1),
("Wednesday","szerda","https://www.angolszokincs.com/st/snw/wednesday.mp3",1),
("date","dátum, időpont","https://www.angolszokincs.com/st/snw/date.mp3",1),
("time","idő","https://www.angolszokincs.com/st/snw/time.mp3",1),
("today","ma","https://www.angolszokincs.com/st/snw/today.mp3",1),
("tomorrow","holnap","https://www.angolszokincs.com/st/snw/tomorrow.mp3",1),
("now","most, jelenleg","https://www.angolszokincs.com/st/snw/now.mp3",1),
("past","múlt","https://www.angolszokincs.com/st/snw/past.mp3",1),
("then","akkor","https://www.angolszokincs.com/st/snw/then.mp3",1),
("today","ma","https://www.angolszokincs.com/st/snw/today.mp3",1),
("tomorrow","holnap","https://www.angolszokincs.com/st/snw/tomorrow.mp3",1),
("tonight","ma este/éjjel","https://www.angolszokincs.com/st/snw/tonight.mp3",1),
("when","mikor?","https://www.angolszokincs.com/st/snw/when.mp3",1),
("yesterday","tegnap","https://www.angolszokincs.com/st/snw/yesterday.mp3",1),
("this","ez, ezen; ma","https://www.angolszokincs.com/st/snw/this.mp3",1),
("at","-kor","https://www.angolszokincs.com/st/snw/at.mp3",1),
("on","vmelyik napon, vmelyik dátumon","https://www.angolszokincs.com/st/snw/on.mp3",1),
("to","múlva","https://www.angolszokincs.com/st/snw/to.mp3",1),
("half past one/two/three, etc.","fél kettő/három/négy","https://www.angolszokincs.com/st/snk/r1399.mp3",1),
("in the morning","reggel","https://www.angolszokincs.com/st/snk/r1614.mp3",1),
("last night","múlt éjjel","https://www.angolszokincs.com/st/snk/r1748.mp3",1),
("last week/year/Monday, etc.","előző/múlt héten/évben/hétfőn/stb.","https://www.angolszokincs.com/st/snk/r1749.mp3",1),
("next week/year/Monday, etc.","következő héten/évben/hétfőn/stb.","https://www.angolszokincs.com/st/snk/r1952.mp3",1),
("one/two/three, etc. o'clock","egy/kettő/három/stb. óra","https://www.angolszokincs.com/st/snk/r2088.mp3",1),
("end","vég","https://www.angolszokincs.com/st/snw/end.mp3",1),
("fast","gyors, sebes","https://www.angolszokincs.com/st/snw/fast.mp3",1),
("late","késő","https://www.angolszokincs.com/st/snw/late.mp3",1),
("late","késő, késői","https://www.angolszokincs.com/st/snw/late.mp3",1),
("long","hosszú, hosszan tartó, hosszadalmas","https://www.angolszokincs.com/st/snw/long.mp3",1),
("quick","gyors","https://www.angolszokincs.com/st/snw/quick.mp3",1),
("short","rövid","https://www.angolszokincs.com/st/snw/short.mp3",1),
("slow","lassú","https://www.angolszokincs.com/st/snw/slow.mp3",1),
("again","újra, megint","https://www.angolszokincs.com/st/snw/again.mp3",1),
("always","mindig","https://www.angolszokincs.com/st/snw/always.mp3",1),
("early","korán","https://www.angolszokincs.com/st/snw/early.mp3",1),
("first","először","https://www.angolszokincs.com/st/snw/first.mp3",1),
("never","soha","https://www.angolszokincs.com/st/snw/never.mp3",1),
("often","gyakran, sokszor","https://www.angolszokincs.com/st/snw/often.mp3",1),
("sometimes","időnként, néha","https://www.angolszokincs.com/st/snw/sometimes.mp3",1),
("then","azután","https://www.angolszokincs.com/st/snw/then.mp3",1),
("all","egész","https://www.angolszokincs.com/st/snw/all.mp3",1),
("every","minden","https://www.angolszokincs.com/st/snw/every.mp3",1),
("after","után","https://www.angolszokincs.com/st/snw/after.mp3",1),
("before","előtt","https://www.angolszokincs.com/st/snw/before.mp3",1),
("between","között, közé","https://www.angolszokincs.com/st/snw/between.mp3",1),
("for","vmennyi ideje/ideig/időre; vmilyen távolságnyit","https://www.angolszokincs.com/st/snw/for.mp3",1),
("from","-tól, -től","https://www.angolszokincs.com/st/snw/from.mp3",1),
("in","-ban, -ben-, folyamán","https://www.angolszokincs.com/st/snw/in.mp3",1),
("until","-ig","https://www.angolszokincs.com/st/snw/until.mp3",1),
("and","és","https://www.angolszokincs.com/st/snw/and.mp3",1),
("no","nem; nincs","https://www.angolszokincs.com/st/snw/no.mp3",1),
("not","nem","https://www.angolszokincs.com/st/snw/not.mp3",1),
("not","nem, ne","https://www.angolszokincs.com/st/snw/not.mp3",1),
("yes","igen","https://www.angolszokincs.com/st/snw/yes.mp3",1),
("all right","jó, rendben","https://www.angolszokincs.com/st/snw/all_right.mp3",1),
("alright","jó, rendben van","https://www.angolszokincs.com/st/snw/alright.mp3",1),
("OK","oké, rendben van","https://www.angolszokincs.com/st/snw/ok.mp3",1),
("of course","természetesen, persze","https://www.angolszokincs.com/st/snk/r2020.mp3",1),
("(that's) fine","jól van! nagyszerű! remek!","https://www.angolszokincs.com/st/snk/r32.mp3",1),
("answer","válaszol, felel vmire","https://www.angolszokincs.com/st/snw/answer.mp3",1),
("ask","kérdez, megkérdez","https://www.angolszokincs.com/st/snw/ask.mp3",1),
("know","tudja hogy ...?","https://www.angolszokincs.com/st/snw/know.mp3",1),
("listen","hallgat vkit/vmit; figyel","https://www.angolszokincs.com/st/snw/listen.mp3",1),
("read","olvas","https://www.angolszokincs.com/st/snw/read.mp3",1),
("speak","beszél","https://www.angolszokincs.com/st/snw/speak.mp3",1),
("talk","beszél, beszélget","https://www.angolszokincs.com/st/snw/talk.mp3",1),
("tell","mond, elmond, megmond; mesél vkinek vmiről","https://www.angolszokincs.com/st/snw/tell.mp3",1),
("understand","ért, megért vmit","https://www.angolszokincs.com/st/snw/understand.mp3",1),
("write","ír, leír","https://www.angolszokincs.com/st/snw/write.mp3",1),
("answer","válasz, felelet","https://www.angolszokincs.com/st/snw/answer.mp3",1),
("book","könyv","https://www.angolszokincs.com/st/snw/book.mp3",1),
("conversation","beszélgetés, társalgás","https://www.angolszokincs.com/st/snw/conversation.mp3",1),
("cross","kereszt, átikszelés","https://www.angolszokincs.com/st/snw/cross.mp3",1),
("letter","levél","https://www.angolszokincs.com/st/snw/letter.mp3",1),
("message","üzenet","https://www.angolszokincs.com/st/snw/message.mp3",1),
("note","pár soros üzenet/levél; feljegyzés","https://www.angolszokincs.com/st/snw/note.mp3",1),
("number","sorszám","https://www.angolszokincs.com/st/snw/number.mp3",1),
("page","oldal, lap","https://www.angolszokincs.com/st/snw/page.mp3",1),
("question","kérdés","https://www.angolszokincs.com/st/snw/question.mp3",1),
("reading","olvasás","https://www.angolszokincs.com/st/snw/reading.mp3",1),
("writing","írás","https://www.angolszokincs.com/st/snw/writing.mp3",1),
("dear","Drága/Kedves/Tisztelt ...","https://www.angolszokincs.com/st/snw/dear.mp3",1),
("yes","igen? tessék?","https://www.angolszokincs.com/st/snw/yes.mp3",1),
("paint","fest, megfest","https://www.angolszokincs.com/st/snw/paint.mp3",1),
("sing","énekel, elénekel, dalol","https://www.angolszokincs.com/st/snw/sing.mp3",1),
("band","együttes, zenekar","https://www.angolszokincs.com/st/snw/band.mp3",1),
("cinema","mozi, filmszínház","https://www.angolszokincs.com/st/snw/cinema.mp3",1),
("film","film, játékfilm","https://www.angolszokincs.com/st/snw/film.mp3",1),
("group","","https://www.angolszokincs.com/st/snw/group.mp3",1),
("guitar","gitár","https://www.angolszokincs.com/st/snw/guitar.mp3",1),
("movie","film, mozifilm","https://www.angolszokincs.com/st/snw/movie.mp3",1),
("museum","múzeum","https://www.angolszokincs.com/st/snw/museum.mp3",1),
("music","zene","https://www.angolszokincs.com/st/snw/music.mp3",1),
("picture","kép","https://www.angolszokincs.com/st/snw/picture.mp3",1),
("famous","híres","https://www.angolszokincs.com/st/snw/famous.mp3",1),
("do","tanul","https://www.angolszokincs.com/st/snw/do.mp3",1),
("learn","tanul, megtanul, elsajátít","https://www.angolszokincs.com/st/snw/learn.mp3",1),
("study","tanul vmit","https://www.angolszokincs.com/st/snw/study.mp3",1),
("teach","tanít","https://www.angolszokincs.com/st/snw/teach.mp3",1),
("board","tábla","https://www.angolszokincs.com/st/snw/board.mp3",1),
("class","","https://www.angolszokincs.com/st/snw/class.mp3",1),
("class","óra","https://www.angolszokincs.com/st/snw/class.mp3",1),
("classroom","tanterem","https://www.angolszokincs.com/st/snw/classroom.mp3",1),
("course","tanfolyam","https://www.angolszokincs.com/st/snw/course.mp3",1),
("homework","házi feladat","https://www.angolszokincs.com/st/snw/homework.mp3",1),
("lesson","tanítási óra, tanóra","https://www.angolszokincs.com/st/snw/lesson.mp3",1),
("pen","toll","https://www.angolszokincs.com/st/snw/pen.mp3",1),
("pencil","ceruza","https://www.angolszokincs.com/st/snw/pencil.mp3",1),
("school","iskola","https://www.angolszokincs.com/st/snw/school.mp3",1),
("student","diák, hallgató","https://www.angolszokincs.com/st/snw/student.mp3",1),
("subject","tantárgy","https://www.angolszokincs.com/st/snw/subject_noun.mp3",1),
("teacher","tanár; tanárnő","https://www.angolszokincs.com/st/snw/teacher.mp3",1),
("test","teszt, vizsga","https://www.angolszokincs.com/st/snw/test.mp3",1),
("university","egyetem","https://www.angolszokincs.com/st/snw/university.mp3",1),
("city","nagyváros","https://www.angolszokincs.com/st/snw/city.mp3",1),
("farm","farm, gazdaság","https://www.angolszokincs.com/st/snw/farm.mp3",1),
("park","park","https://www.angolszokincs.com/st/snw/park.mp3",1),
("town","város","https://www.angolszokincs.com/st/snw/town.mp3",1),
("village","falu","https://www.angolszokincs.com/st/snw/village.mp3",1),
("catch","felszáll","https://www.angolszokincs.com/st/snw/catch.mp3",1),
("drive","vezet","https://www.angolszokincs.com/st/snw/drive.mp3",1),
("fly","repül, repülőn utazik","https://www.angolszokincs.com/st/snw/fly.mp3",1),
("ride","lovagol; kerékpározik; motorozik","https://www.angolszokincs.com/st/snw/ride.mp3",1),
("travel","utazik, utat megtesz","https://www.angolszokincs.com/st/snw/travel.mp3",1),
("boat","csónak; hajó","https://www.angolszokincs.com/st/snw/boat.mp3",1),
("bus","busz, autóbusz","https://www.angolszokincs.com/st/snw/bus.mp3",1),
("car","autó, személyautó","https://www.angolszokincs.com/st/snw/car.mp3",1),
("driver","sofőr, -vezető","https://www.angolszokincs.com/st/snw/driver.mp3",1),
("plane","repülőgép","https://www.angolszokincs.com/st/snw/plane.mp3",1),
("road","út, közút","https://www.angolszokincs.com/st/snw/road.mp3",1),
("station","vasútállomás; állomás","https://www.angolszokincs.com/st/snw/station.mp3",1),
("stop","megálló","https://www.angolszokincs.com/st/snw/stop.mp3",1),
("street","utca","https://www.angolszokincs.com/st/snw/street.mp3",1),
("taxi","taxi","https://www.angolszokincs.com/st/snw/taxi.mp3",1),
("ticket","jegy","https://www.angolszokincs.com/st/snw/ticket.mp3",1),
("train","vonat","https://www.angolszokincs.com/st/snw/train.mp3",1),
("get a bus/train/taxi, etc.","busszal/vonattal/taxival megy/utazik","https://www.angolszokincs.com/st/snk/r1250.mp3",1),
("be","van, valaki/valami valahol van","https://www.angolszokincs.com/st/snw/be.mp3",1),
("begin","kezdődik, elkezdődik","https://www.angolszokincs.com/st/snw/begin.mp3",1),
("change","vált, változtat","https://www.angolszokincs.com/st/snw/change.mp3",1),
("choose","választ","https://www.angolszokincs.com/st/snw/choose.mp3",1),
("find","talál, megtalál","https://www.angolszokincs.com/st/snw/find.mp3",1),
("finish","befejez","https://www.angolszokincs.com/st/snw/finish.mp3",1),
("finish","befejeződik","https://www.angolszokincs.com/st/snw/finish.mp3",1),
("get","kap, megkap","https://www.angolszokincs.com/st/snw/get.mp3",1),
("give","ad vmit vkinek","https://www.angolszokincs.com/st/snw/give.mp3",1),
("look","keres","https://www.angolszokincs.com/st/snw/look.mp3",1),
("send","küld, elküld vkinek vmit","https://www.angolszokincs.com/st/snw/send.mp3",1),
("start","elkezd vmit","https://www.angolszokincs.com/st/snw/start.mp3",1),
("stop","abbahagy; megszüntet; megszűnik","https://www.angolszokincs.com/st/snw/stop.mp3",1),
("use","használ vmit; igénybe vesz vmit","https://www.angolszokincs.com/st/snw/use_verb.mp3",1),
("there is/are/was, etc.","van, vannak/volt/stb.","https://www.angolszokincs.com/st/snk/r2852.mp3",1),
("work","dolgozik","https://www.angolszokincs.com/st/snw/work.mp3",1),
("job","állás","https://www.angolszokincs.com/st/snw/job.mp3",1),
("waiter","pincér","https://www.angolszokincs.com/st/snw/waiter.mp3",1),
("waitress","pincérnő","https://www.angolszokincs.com/st/snw/waitress.mp3",1),
("work","munka, munkahely","https://www.angolszokincs.com/st/snw/work.mp3",1),
("work","munka","https://www.angolszokincs.com/st/snw/work.mp3",1),
("as","vmiként, mint vmi","https://www.angolszokincs.com/st/snw/as.mp3",1),
("I am Spanish/a teacher, etc.","spanyol/tanár/stb. vagyok","https://www.angolszokincs.com/st/snk/r66.mp3",1),
("what does sb do?","mi a foglalkozása?","https://www.angolszokincs.com/st/snk/r2998.mp3",1),
("phone","telefonál","https://www.angolszokincs.com/st/snw/phone.mp3",1),
("address","","https://www.angolszokincs.com/st/snw/address.mp3",1),
("computer","számítógép","https://www.angolszokincs.com/st/snw/computer.mp3",1),
("email","e-mail, elektronikus levelezés","https://www.angolszokincs.com/st/snw/email.mp3",1),
("email","e-mail, elektronikus levél","https://www.angolszokincs.com/st/snw/email.mp3",1),
("mobile","mobiltelefon","https://www.angolszokincs.com/st/snw/mobile.mp3",1),
("mobile phone","mobiltelefon","https://www.angolszokincs.com/st/snw/mobile_phone.mp3",1),
("newspaper","újság, napilap, hetilap","https://www.angolszokincs.com/st/snw/newspaper.mp3",1),
("number","szám, telefonszám","https://www.angolszokincs.com/st/snw/number.mp3",1),
("phone","telefon, telefonkészülék","https://www.angolszokincs.com/st/snw/phone.mp3",1),
("television","televízió, televízióadás","https://www.angolszokincs.com/st/snw/television.mp3",1),
("the Internet","az internet","https://www.angolszokincs.com/st/snw/the_internet.mp3",1),
("website","webhely, honlap","https://www.angolszokincs.com/st/snw/website.mp3",1),
("here","itt","https://www.angolszokincs.com/st/snw/here.mp3",1),
("at","az @ jel az e-mail címekben","https://www.angolszokincs.com/st/snw/at.mp3",1),
("hello","halló!","https://www.angolszokincs.com/st/snw/hello.mp3",1),
("the radio","a rádió","https://www.angolszokincs.com/st/snk/r2806.mp3",1),
("say","mond","https://www.angolszokincs.com/st/snw/say.mp3",1),
("speak","beszél","https://www.angolszokincs.com/st/snw/speak.mp3",1),
("dictionary","szótár; lexikon","https://www.angolszokincs.com/st/snw/dictionary.mp3",1),
("language","nyelv","https://www.angolszokincs.com/st/snw/language.mp3",1),
("sentence","mondat","https://www.angolszokincs.com/st/snw/sentence.mp3",1),
("word","szó","https://www.angolszokincs.com/st/snw/word.mp3",1),
("the present","jelen idő","https://www.angolszokincs.com/st/snk/r2801.mp3",1),
("swim","úszik","https://www.angolszokincs.com/st/snw/swim.mp3",1),
("ball","labda, golyó, gömbölyű tárgy","https://www.angolszokincs.com/st/snw/ball.mp3",1),
("basketball","kosárlabda","https://www.angolszokincs.com/st/snw/basketball.mp3",1),
("football","futball","https://www.angolszokincs.com/st/snw/football.mp3",1),
("football","futball-labda","https://www.angolszokincs.com/st/snw/football.mp3",1),
("player","játékos","https://www.angolszokincs.com/st/snw/player.mp3",1),
("sport","sport, sportág","https://www.angolszokincs.com/st/snw/sport.mp3",1),
("sport","sport, sportolás","https://www.angolszokincs.com/st/snw/sport.mp3",1),
("tennis","tenisz","https://www.angolszokincs.com/st/snw/tennis.mp3",1),
("between","között","https://www.angolszokincs.com/st/snw/between.mp3",1),
("adult","felnőtt","https://www.angolszokincs.com/st/snw/adult.mp3",1),
("age","kor, életkor","https://www.angolszokincs.com/st/snw/age.mp3",1),
("baby","csecsemő, kisbaba","https://www.angolszokincs.com/st/snw/baby.mp3",1),
("boy","fiú","https://www.angolszokincs.com/st/snw/boy.mp3",1),
("child","gyerek","https://www.angolszokincs.com/st/snw/child.mp3",1),
("girl","lány; lánya vkinek; fiatal nő","https://www.angolszokincs.com/st/snw/girl.mp3",1),
("man","férfi","https://www.angolszokincs.com/st/snw/man.mp3",1),
("people","emberek","https://www.angolszokincs.com/st/snw/people.mp3",1),
("person","személy","https://www.angolszokincs.com/st/snw/person.mp3",1),
("woman","asszony, nő","https://www.angolszokincs.com/st/snw/woman.mp3",1),
("little","kicsi, kis","https://www.angolszokincs.com/st/snw/little.mp3",1),
("old","öreg, koros, idős","https://www.angolszokincs.com/st/snw/old.mp3",1),
("old","vmennyi idős, vhány éves","https://www.angolszokincs.com/st/snw/old.mp3",1),
("small","kis, kicsi","https://www.angolszokincs.com/st/snw/small.mp3",1),
("young","fiatal","https://www.angolszokincs.com/st/snw/young.mp3",1),
("be ... years old","... éves","https://www.angolszokincs.com/st/snk/r435.mp3",1),
("address","cím","https://www.angolszokincs.com/st/snw/address.mp3",1),
("Miss","kisasszony","https://www.angolszokincs.com/st/snw/miss.mp3",1),
("Mr","úr","https://www.angolszokincs.com/st/snw/mr.mp3",1),
("Mrs","-né, asszony","https://www.angolszokincs.com/st/snw/mrs.mp3",1),
("name","név","https://www.angolszokincs.com/st/snw/name.mp3",1),
("nationality","állampolgárság","https://www.angolszokincs.com/st/snw/nationality.mp3",1),
("clever","okos, értelmes","https://www.angolszokincs.com/st/snw/clever.mp3",1),
("good","jó vmiben, ért vmihez","https://www.angolszokincs.com/st/snw/good.mp3",1),
("from","-ból, -ből","https://www.angolszokincs.com/st/snw/from.mp3",1),
("come from swh/sth","jön , származik  vhonnan vhonnan/vmiből","https://www.angolszokincs.com/st/snk/r898.mp3",1),
("be called sth","hívják , nevezik  vhogy vhogy  vhol","https://www.angolszokincs.com/st/snk/r478.mp3",1),
("live in/at, etc.","lakik  vhogy vhogy  vhol","https://www.angolszokincs.com/st/snk/r1808.mp3",1),
("Road","... út  vhogy vhogy  vhol","https://www.angolszokincs.com/st/snk/r105.mp3",1),
("Street","utca  vhogy vhogy  vhol","https://www.angolszokincs.com/st/snk/r106.mp3",1),
("eight","nyolc","https://www.angolszokincs.com/st/snw/eight.mp3",1),
("five","öt","https://www.angolszokincs.com/st/snw/five.mp3",1),
("four","négy","https://www.angolszokincs.com/st/snw/four.mp3",1),
("nine","kilenc","https://www.angolszokincs.com/st/snw/nine.mp3",1),
("one","egy","https://www.angolszokincs.com/st/snw/one.mp3",1),
("seven","hét","https://www.angolszokincs.com/st/snw/seven.mp3",1),
("six","hat","https://www.angolszokincs.com/st/snw/six.mp3",1),
("ten","tíz","https://www.angolszokincs.com/st/snw/ten.mp3",1),
("three","három","https://www.angolszokincs.com/st/snw/three.mp3",1),
("two","kettő","https://www.angolszokincs.com/st/snw/two.mp3",1),
("eighteen","tizennyolc","https://www.angolszokincs.com/st/snw/eighteen.mp3",1),
("eleven","tizenegy","https://www.angolszokincs.com/st/snw/eleven.mp3",1),
("fifteen","tizenöt","https://www.angolszokincs.com/st/snw/fifteen.mp3",1),
("fourteen","tizennégy","https://www.angolszokincs.com/st/snw/fourteen.mp3",1),
("nineteen","tizenkilenc","https://www.angolszokincs.com/st/snw/nineteen.mp3",1),
("seventeen","tizenhét","https://www.angolszokincs.com/st/snw/seventeen.mp3",1),
("sixteen","tizenhat","https://www.angolszokincs.com/st/snw/sixteen.mp3",1),
("thirteen","tizenhárom","https://www.angolszokincs.com/st/snw/thirteen.mp3",1),
("twelve","tizenkettő","https://www.angolszokincs.com/st/snw/twelve.mp3",1),
("twenty","húsz","https://www.angolszokincs.com/st/snw/twenty.mp3",1),
("number","szám, számjegy","https://www.angolszokincs.com/st/snw/number.mp3",1),
("some","néhány, némi","https://www.angolszokincs.com/st/snw/some.mp3",1),
("some","néhány","https://www.angolszokincs.com/st/snw/some.mp3",1),
("first","első","https://www.angolszokincs.com/st/snw/first.mp3",1),
("little","kicsi, kis","https://www.angolszokincs.com/st/snw/little.mp3",1),
("only","az egyetlen, egyedüli","https://www.angolszokincs.com/st/snw/only.mp3",1),
("about","körülbelül","https://www.angolszokincs.com/st/snw/about.mp3",1),
("how","hány, mennyi, milyen","https://www.angolszokincs.com/st/snw/how.mp3",1),
("only","csak","https://www.angolszokincs.com/st/snw/only.mp3",1),
("a","egy","https://www.angolszokincs.com/st/snw/a.mp3",1),
("many","sok","https://www.angolszokincs.com/st/snw/many.mp3",1),
("more","több","https://www.angolszokincs.com/st/snw/more.mp3",1),
("more","több","https://www.angolszokincs.com/st/snw/more.mp3",1),
("much","","https://www.angolszokincs.com/st/snw/much.mp3",1),
("second","második","https://www.angolszokincs.com/st/snw/second.mp3",1),
("some","néhány, némi","https://www.angolszokincs.com/st/snw/some.mp3",1),
("of","valamennyi valakiből/valamiből","https://www.angolszokincs.com/st/snw/of.mp3",1),
("of","szám, dátum, életkor kifejezése","https://www.angolszokincs.com/st/snw/of.mp3",1),
("and","meg","https://www.angolszokincs.com/st/snw/and.mp3",1),
("a lot/lots","sok, rengeteg","https://www.angolszokincs.com/st/snk/r185.mp3",1),
("how many","hány? mennyi?","https://www.angolszokincs.com/st/snk/r1486.mp3",1),
("want","akar vmit; kíván vmit/vkit","https://www.angolszokincs.com/st/snw/want.mp3",1),
("will","óhajt, kíván","https://www.angolszokincs.com/st/snw/will.mp3",1),
("ready","kész, készen áll vmire","https://www.angolszokincs.com/st/snw/ready.mp3",1),
("hard","keményen, szorgalmasan","https://www.angolszokincs.com/st/snw/hard.mp3",1),
("would like sth/to do sth","szeretne  vmit/csinálni vmit","https://www.angolszokincs.com/st/snk/r3048.mp3",1),
("Would you like ...?","szeretne ...?  vmit/csinálni vmit","https://www.angolszokincs.com/st/snk/r116.mp3",1),
("need","szüksége van vmire/vkire","https://www.angolszokincs.com/st/snw/need.mp3",1),
("can","tud","https://www.angolszokincs.com/st/snw/can_2.mp3",1),
("can","-hat, -het","https://www.angolszokincs.com/st/snw/can_2.mp3",1),
("cannot","","https://www.angolszokincs.com/st/snw/cannot.mp3",1),
("possible","lehetséges","https://www.angolszokincs.com/st/snw/possible.mp3",1),
("need to do sth","kell","https://www.angolszokincs.com/st/snk/r1944.mp3",1),
("animal","állat","https://www.angolszokincs.com/st/snw/animal.mp3",1),
("beach","tengerpart","https://www.angolszokincs.com/st/snw/beach.mp3",1),
("bird","madár","https://www.angolszokincs.com/st/snw/bird.mp3",1),
("cat","macska","https://www.angolszokincs.com/st/snw/cat.mp3",1),
("cow","tehén","https://www.angolszokincs.com/st/snw/cow.mp3",1),
("dog","kutya","https://www.angolszokincs.com/st/snw/dog.mp3",1),
("fish","hal","https://www.angolszokincs.com/st/snw/fish.mp3",1),
("flower","virág","https://www.angolszokincs.com/st/snw/flower.mp3",1),
("grass","fű","https://www.angolszokincs.com/st/snw/grass.mp3",1),
("horse","ló","https://www.angolszokincs.com/st/snw/horse.mp3",1),
("pet","kedvtelésből tartott kisállat","https://www.angolszokincs.com/st/snw/pet.mp3",1),
("pig","disznó, sertés","https://www.angolszokincs.com/st/snw/pig.mp3",1),
("plant","növény","https://www.angolszokincs.com/st/snw/plant.mp3",1),
("rain","eső","https://www.angolszokincs.com/st/snw/rain.mp3",1),
("river","folyó","https://www.angolszokincs.com/st/snw/river.mp3",1),
("sea","tenger","https://www.angolszokincs.com/st/snw/sea.mp3",1),
("sheep","birka","https://www.angolszokincs.com/st/snw/sheep.mp3",1),
("snow","hó","https://www.angolszokincs.com/st/snw/snow.mp3",1),
("sun","nap ; napfény","https://www.angolszokincs.com/st/snw/sun.mp3",1),
("tree","fa","https://www.angolszokincs.com/st/snw/tree.mp3",1),
("weather","idő, időjárás","https://www.angolszokincs.com/st/snw/weather.mp3",1),
("wind","szél","https://www.angolszokincs.com/st/snw/wind_1.mp3",1),
("world","világ, föld","https://www.angolszokincs.com/st/snw/world.mp3",1),
("cold","hideg","https://www.angolszokincs.com/st/snw/cold.mp3",1),
("hot","forró","https://www.angolszokincs.com/st/snw/hot.mp3",1),
("warm","meleg","https://www.angolszokincs.com/st/snw/warm.mp3",1),
("it rains/it is raining","esik","https://www.angolszokincs.com/st/snk/r1652.mp3",1),
("hear","hall, meghall","https://www.angolszokincs.com/st/snw/hear.mp3",1),
("look","néz, megnéz","https://www.angolszokincs.com/st/snw/look.mp3",1),
("see","lát","https://www.angolszokincs.com/st/snw/see.mp3",1),
("show","mutat, megmutat vmit vkinek","https://www.angolszokincs.com/st/snw/show.mp3",1),
("sleep","alszik","https://www.angolszokincs.com/st/snw/sleep.mp3",1),
("wash","mosakodik, megmosakodik","https://www.angolszokincs.com/st/snw/wash.mp3",1),
("watch","figyel, néz vmit","https://www.angolszokincs.com/st/snw/watch.mp3",1),
("arm","kar","https://www.angolszokincs.com/st/snw/arm.mp3",1),
("bath","fürdés, fürdő; fürdővíz","https://www.angolszokincs.com/st/snw/bath.mp3",1),
("beard","szakáll","https://www.angolszokincs.com/st/snw/beard.mp3",1),
("body","test","https://www.angolszokincs.com/st/snw/body.mp3",1),
("ear","fül","https://www.angolszokincs.com/st/snw/ear.mp3",1),
("eye","szem","https://www.angolszokincs.com/st/snw/eye.mp3",1),
("face","arc","https://www.angolszokincs.com/st/snw/face.mp3",1),
("foot","láb, lábfej","https://www.angolszokincs.com/st/snw/foot.mp3",1),
("hair","haj; szőr, szőrzet","https://www.angolszokincs.com/st/snw/hair.mp3",1),
("hand","kéz, kézfej","https://www.angolszokincs.com/st/snw/hand.mp3",1),
("head","fej","https://www.angolszokincs.com/st/snw/head.mp3",1),
("leg","láb, lábszár","https://www.angolszokincs.com/st/snw/leg.mp3",1),
("life","élet, életidő","https://www.angolszokincs.com/st/snw/life.mp3",1),
("mouth","száj","https://www.angolszokincs.com/st/snw/mouth.mp3",1),
("nose","orr","https://www.angolszokincs.com/st/snw/nose.mp3",1),
("shower","zuhany, zuhanyozás","https://www.angolszokincs.com/st/snw/shower.mp3",1),
("tooth","fog","https://www.angolszokincs.com/st/snw/tooth.mp3",1),
("fat","kövér, elhízott","https://www.angolszokincs.com/st/snw/fat.mp3",1),
("fine","jól van","https://www.angolszokincs.com/st/snw/fine.mp3",1),
("good","jól van, egészséges","https://www.angolszokincs.com/st/snw/good.mp3",1),
("OK","jól van, rendben van","https://www.angolszokincs.com/st/snw/ok.mp3",1),
("slim","karcsú, vékony","https://www.angolszokincs.com/st/snw/slim.mp3",1),
("sweet","édes","https://www.angolszokincs.com/st/snw/sweet.mp3",1),
("tall","magas","https://www.angolszokincs.com/st/snw/tall.mp3",1),
("tired","fáradt","https://www.angolszokincs.com/st/snw/tired.mp3",1),
("well","jól van, egészséges","https://www.angolszokincs.com/st/snw/well.mp3",1),
("get (sb) up","felkel; felkelt","https://www.angolszokincs.com/st/snk/r1248.mp3",1),
("wake up ↔ (sb)","felébred; felébreszt","https://www.angolszokincs.com/st/snk/r2987.mp3",1),
("good for you","jót tesz  vkinek","https://www.angolszokincs.com/st/snk/r1385.mp3",1),
("How are you?","hogy van? hogy vagy?  vkinek","https://www.angolszokincs.com/st/snk/r62.mp3",1),
("country","ország","https://www.angolszokincs.com/st/snw/country.mp3",1),
("bottom","alja vminek, alsó része vminek","https://www.angolszokincs.com/st/snw/bottom.mp3",1),
("place","hely, helyszín","https://www.angolszokincs.com/st/snw/place.mp3",1),
("close","közel, közeli","https://www.angolszokincs.com/st/snw/close_adj.mp3",1),
("above","felett, felül, fent; fölé","https://www.angolszokincs.com/st/snw/above.mp3",1),
("back","vissza","https://www.angolszokincs.com/st/snw/back.mp3",1),
("below","alatt, alá","https://www.angolszokincs.com/st/snw/below.mp3",1),
("down","le","https://www.angolszokincs.com/st/snw/down.mp3",1),
("here","itt; ide; innen","https://www.angolszokincs.com/st/snw/here.mp3",1),
("there","ott, oda","https://www.angolszokincs.com/st/snw/there.mp3",1),
("there","oda","https://www.angolszokincs.com/st/snw/there.mp3",1),
("up","fel","https://www.angolszokincs.com/st/snw/up.mp3",1),
("where","hol? hova?","https://www.angolszokincs.com/st/snw/where.mp3",1),
("at","-on, -en, -ön, -ban, -ben, -nál, -nél","https://www.angolszokincs.com/st/snw/at.mp3",1),
("at","-ra, -re","https://www.angolszokincs.com/st/snw/at.mp3",1),
("behind","mögött, mögé","https://www.angolszokincs.com/st/snw/behind.mp3",1),
("between","között, közé","https://www.angolszokincs.com/st/snw/between.mp3",1),
("from","-tól, -től, -ról, -ről, -ból, -ből","https://www.angolszokincs.com/st/snw/from.mp3",1),
("from","-tól, -től","https://www.angolszokincs.com/st/snw/from.mp3",1),
("in","-ban, -ben, -ba, -be","https://www.angolszokincs.com/st/snw/in.mp3",1),
("inside","belül","https://www.angolszokincs.com/st/snw/inside_prep.mp3",1),
("into","-ba, -be","https://www.angolszokincs.com/st/snw/into.mp3",1),
("near","közel","https://www.angolszokincs.com/st/snw/near.mp3",1),
("on","-on, -en, -ön, -ra, -re","https://www.angolszokincs.com/st/snw/on.mp3",1),
("on","-on, -en, -ön, -ra, -re","https://www.angolszokincs.com/st/snw/on.mp3",1),
("to","-ba, -be, -hoz, -hez, -höz, -ra, -re","https://www.angolszokincs.com/st/snw/to.mp3",1),
("under","alatt, alá","https://www.angolszokincs.com/st/snw/under.mp3",1),
("sorry","sajnálja","https://www.angolszokincs.com/st/snw/sorry.mp3",1),
("dance","táncol","https://www.angolszokincs.com/st/snw/dance.mp3",1),
("draw","rajzol, lerajzol","https://www.angolszokincs.com/st/snw/draw.mp3",1),
("play","játszik","https://www.angolszokincs.com/st/snw/play.mp3",1),
("play","játszik","https://www.angolszokincs.com/st/snw/play.mp3",1),
("practise","gyakorol","https://www.angolszokincs.com/st/snw/practise.mp3",1),
("smoke","dohányzik; szív, elszív","https://www.angolszokincs.com/st/snw/smoke.mp3",1),
("stay","marad vhol","https://www.angolszokincs.com/st/snw/stay.mp3",1),
("take","elvisz vkit vhova","https://www.angolszokincs.com/st/snw/take.mp3",1),
("visit","meglátogat","https://www.angolszokincs.com/st/snw/visit.mp3",1),
("wait","vár vkit/vmit","https://www.angolszokincs.com/st/snw/wait.mp3",1),
("bar","bár, kávézó, büfé; bárpult","https://www.angolszokincs.com/st/snw/bar.mp3",1),
("birthday","születésnap","https://www.angolszokincs.com/st/snw/birthday.mp3",1),
("café","eszpresszó, kávéház, kis étterem","https://www.angolszokincs.com/st/snw/cafe.mp3",1),
("camera","fényképezőgép, filmfelvevő gép, kamera","https://www.angolszokincs.com/st/snw/camera.mp3",1),
("dance","tánc","https://www.angolszokincs.com/st/snw/dance.mp3",1),
("dancing","tánc, táncolás","https://www.angolszokincs.com/st/snw/dancing.mp3",1),
("doll","játékbaba","https://www.angolszokincs.com/st/snw/doll.mp3",1),
("fun","szórakozás, jó mulatság","https://www.angolszokincs.com/st/snw/fun.mp3",1),
("game","játék","https://www.angolszokincs.com/st/snw/game.mp3",1),
("holiday","szabadnap; szabadság;","https://www.angolszokincs.com/st/snw/holiday.mp3",1),
("holiday","vakáció, üdülés, nyaralás","https://www.angolszokincs.com/st/snw/holiday.mp3",1),
("photo","fénykép, felvétel","https://www.angolszokincs.com/st/snw/photo.mp3",1),
("picnic","piknik","https://www.angolszokincs.com/st/snw/picnic.mp3",1),
("smoking","dohányzás","https://www.angolszokincs.com/st/snw/smoking.mp3",1),
("zoo","állatkert","https://www.angolszokincs.com/st/snw/zoo.mp3",1),
("funny","vicces, mulatságos","https://www.angolszokincs.com/st/snw/funny.mp3",1),
("poor","szegény","https://www.angolszokincs.com/st/snw/poor.mp3",1),
("outside","kint, odakint","https://www.angolszokincs.com/st/snw/outside_adv.mp3",1),
("go out","elmegy","https://www.angolszokincs.com/st/snk/r1364.mp3",1),
("take a picture/photo(graph)","fényképet készít","https://www.angolszokincs.com/st/snk/r2598.mp3",1),
("kind","fajta, -féle","https://www.angolszokincs.com/st/snw/kind.mp3",1),
("problem","gond, probléma","https://www.angolszokincs.com/st/snw/problem.mp3",1),
("all right","jól, rendben","https://www.angolszokincs.com/st/snw/all_right.mp3",1),
("bad","rossz","https://www.angolszokincs.com/st/snw/bad.mp3",1),
("beautiful","gyönyörű, szép","https://www.angolszokincs.com/st/snw/beautiful.mp3",1),
("beautiful","pompás, remek, csodálatos","https://www.angolszokincs.com/st/snw/beautiful.mp3",1),
("difficult","nehéz, bonyolult","https://www.angolszokincs.com/st/snw/difficult.mp3",1),
("easy","könnyű, egyszerű; kényelmes, gondtalan","https://www.angolszokincs.com/st/snw/easy.mp3",1),
("good","jó","https://www.angolszokincs.com/st/snw/good.mp3",1),
("good","jó","https://www.angolszokincs.com/st/snw/good.mp3",1),
("great","klassz, csodás","https://www.angolszokincs.com/st/snw/great.mp3",1),
("hard","nehéz","https://www.angolszokincs.com/st/snw/hard.mp3",1),
("important","fontos","https://www.angolszokincs.com/st/snw/important.mp3",1),
("right","helyes, igaz","https://www.angolszokincs.com/st/snw/right.mp3",1),
("wrong","rossz, helytelen, hibás","https://www.angolszokincs.com/st/snw/wrong.mp3",1),
("well","jól","https://www.angolszokincs.com/st/snw/well.mp3",1),
("a","egy vmi","https://www.angolszokincs.com/st/snw/a.mp3",1),
("enjoy","élvez vmit, nagyon szeret csinálni vmit","https://www.angolszokincs.com/st/snw/enjoy.mp3",1),
("like","szeret, kedvel, tetszik vkinek vmi/vki","https://www.angolszokincs.com/st/snw/like.mp3",1),
("love","nagyon szeret, imád vmit","https://www.angolszokincs.com/st/snw/love.mp3",1),
("love","nagyon szeret vkit, imád vkit","https://www.angolszokincs.com/st/snw/love.mp3",1),
("bored","unatkozó, unott","https://www.angolszokincs.com/st/snw/bored.mp3",1),
("boring","unalmas","https://www.angolszokincs.com/st/snw/boring.mp3",1),
("excited","izgatott, lelkes","https://www.angolszokincs.com/st/snw/excited.mp3",1),
("exciting","izgalmas","https://www.angolszokincs.com/st/snw/exciting.mp3",1),
("favourite","kedvenc, legkedveltebb","https://www.angolszokincs.com/st/snw/favourite.mp3",1),
("good","jó, kedves, segítőkész","https://www.angolszokincs.com/st/snw/good.mp3",1),
("happy","boldog","https://www.angolszokincs.com/st/snw/happy.mp3",1),
("interesting","érdekes","https://www.angolszokincs.com/st/snw/interesting.mp3",1),
("nice","kellemes","https://www.angolszokincs.com/st/snw/nice.mp3",1),
("nice","kedves","https://www.angolszokincs.com/st/snw/nice.mp3",1),
("sad","szomorú; elszomorító; sajnálatos","https://www.angolszokincs.com/st/snw/sad.mp3",1),
("Don't worry (about sth)","ne aggódj","https://www.angolszokincs.com/st/snk/r52.mp3",1),
("eat","eszik, étkezik","https://www.angolszokincs.com/st/snw/eat.mp3",1),
("beer","sör","https://www.angolszokincs.com/st/snw/beer.mp3",1),
("biscuit","keksz","https://www.angolszokincs.com/st/snw/biscuit.mp3",1),
("breakfast","reggeli","https://www.angolszokincs.com/st/snw/breakfast.mp3",1),
("cake","sütemény, torta","https://www.angolszokincs.com/st/snw/cake.mp3",1),
("chip","hasábburgonya","https://www.angolszokincs.com/st/snw/chip.mp3",1),
("chocolate","csokoládé; csokoládés desszert","https://www.angolszokincs.com/st/snw/chocolate.mp3",1),
("coffee","kávé","https://www.angolszokincs.com/st/snw/coffee.mp3",1),
("dinner","vacsora, ebéd","https://www.angolszokincs.com/st/snw/dinner.mp3",1),
("drink","ital, innivaló","https://www.angolszokincs.com/st/snw/drink.mp3",1),
("ice cream","fagylalt","https://www.angolszokincs.com/st/snw/ice_cream.mp3",1),
("juice","lé, gyümölcslé, zöldséglé","https://www.angolszokincs.com/st/snw/juice.mp3",1),
("lunch","ebéd","https://www.angolszokincs.com/st/snw/lunch.mp3",1),
("meal","étkezés; étel","https://www.angolszokincs.com/st/snw/meal.mp3",1),
("pizza","pizza","https://www.angolszokincs.com/st/snw/pizza.mp3",1),
("soup","leves","https://www.angolszokincs.com/st/snw/soup.mp3",1),
("tea","tea","https://www.angolszokincs.com/st/snw/tea.mp3",1),
("wine","bor","https://www.angolszokincs.com/st/snw/wine.mp3",1),
("cook","főz ; fő, sül","https://www.angolszokincs.com/st/snw/cook.mp3",1),
("drink","iszik","https://www.angolszokincs.com/st/snw/drink.mp3",1),
("eat","eszik, megeszik","https://www.angolszokincs.com/st/snw/eat.mp3",1),
("have","eszik/iszik vmit","https://www.angolszokincs.com/st/snw/have.mp3",1),
("apple","alma","https://www.angolszokincs.com/st/snw/apple.mp3",1),
("banana","banán","https://www.angolszokincs.com/st/snw/banana.mp3",1),
("bread","kenyér","https://www.angolszokincs.com/st/snw/bread.mp3",1),
("butter","vaj","https://www.angolszokincs.com/st/snw/butter.mp3",1),
("cheese","sajt","https://www.angolszokincs.com/st/snw/cheese.mp3",1),
("egg","tojás","https://www.angolszokincs.com/st/snw/egg.mp3",1),
("fish","hal","https://www.angolszokincs.com/st/snw/fish.mp3",1),
("food","ennivaló, élelmiszer","https://www.angolszokincs.com/st/snw/food.mp3",1),
("fruit","gyümölcs","https://www.angolszokincs.com/st/snw/fruit.mp3",1),
("meat","hús","https://www.angolszokincs.com/st/snw/meat.mp3",1),
("milk","tej","https://www.angolszokincs.com/st/snw/milk.mp3",1),
("orange","narancs","https://www.angolszokincs.com/st/snw/orange.mp3",1),
("potato","burgonya, krumpli","https://www.angolszokincs.com/st/snw/potato.mp3",1),
("rice","rizs","https://www.angolszokincs.com/st/snw/rice.mp3",1),
("salt","só, konyhasó","https://www.angolszokincs.com/st/snw/salt.mp3",1),
("sandwich","szendvics","https://www.angolszokincs.com/st/snw/sandwich.mp3",1),
("sugar","cukor","https://www.angolszokincs.com/st/snw/sugar.mp3",1),
("tomato","paradicsom","https://www.angolszokincs.com/st/snw/tomato.mp3",1),
("vegetable","zöldség","https://www.angolszokincs.com/st/snw/vegetable.mp3",1),
("hungry","éhes","https://www.angolszokincs.com/st/snw/hungry.mp3",1),
("wear","hord, visel","https://www.angolszokincs.com/st/snw/wear.mp3",1),
("clothes","ruha, ruhanemű","https://www.angolszokincs.com/st/snw/clothes.mp3",1),
("coat","kabát","https://www.angolszokincs.com/st/snw/coat.mp3",1),
("dress","női ruha","https://www.angolszokincs.com/st/snw/dress.mp3",1),
("glasses","szemüveg","https://www.angolszokincs.com/st/snw/glasses.mp3",1),
("hat","kalap, sapka","https://www.angolszokincs.com/st/snw/hat.mp3",1),
("jacket","zakó","https://www.angolszokincs.com/st/snw/jacket.mp3",1),
("jeans","farmer, farmernadrág","https://www.angolszokincs.com/st/snw/jeans.mp3",1),
("shirt","ing","https://www.angolszokincs.com/st/snw/shirt.mp3",1),
("shoe","cipő","https://www.angolszokincs.com/st/snw/shoe.mp3",1),
("skirt","szoknya","https://www.angolszokincs.com/st/snw/skirt.mp3",1),
("T-shirt","póló, pólóing","https://www.angolszokincs.com/st/snw/t-shirt.mp3",1),
("trousers","nadrág","https://www.angolszokincs.com/st/snw/trousers.mp3",1),
("watch","karóra","https://www.angolszokincs.com/st/snw/watch.mp3",1);